# stolen from 3256 who stole it from 8033

name: Spotless-Apply

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job
  spotless-apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Runs a single command using the runners shell
      - name: Apply spotless formatting
        run: ./gradlew spotlessApply

      # Commit changes
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: run spotless
